In [106]:
import pandas as pd

In [107]:
movies=pd.read_csv('dataset.csv')

In [108]:
movies=movies[['id', 'title', 'overview', 'genre']]

In [109]:
movies['tags'] = movies['overview']+movies['genre']

In [110]:
new_data  = movies.drop(columns=['overview', 'genre'])

In [111]:
# Get 20 random rows from the DataFrame
movies_history = movies.sample(n=20, random_state=42).reset_index(drop=True)

In [112]:
# Display the randomly selected rows
movies_history

,id,title,overview,genre,tags
0,332567,The Shallows,"When Nancy is surfing on a secluded beach, she...","Horror,Drama,Thriller","When Nancy is surfing on a secluded beach, she..."
1,727293,The Tender Bar,J.R. is a fatherless boy growing up in the glo...,Drama,J.R. is a fatherless boy growing up in the glo...
2,9385,The Twelve Tasks of Asterix,Asterix and Obelix depart on an adventure to c...,"Family,Animation,Comedy,Adventure",Asterix and Obelix depart on an adventure to c...
3,635731,Pig,A truffle hunter who lives alone in the Oregon...,"Drama,Thriller",A truffle hunter who lives alone in the Oregon...
4,8835,Legally Blonde,"Elle Woods, a fashionable sorority queen, is d...",Comedy,"Elle Woods, a fashionable sorority queen, is d..."
5,38365,Grown Ups,After their high school basketball coach passe...,Comedy,After their high school basketball coach passe...
6,5991,The Last Laugh,"An aging doorman, after being fired from his p...",Drama,"An aging doorman, after being fired from his p..."
7,390062,Jungle,"In 1981, an enthusiastic young adventurer foll...","Adventure,Drama,Thriller","In 1981, an enthusiastic young adventurer foll..."
8,82675,Taken 2,"In Istanbul, retired CIA operative Bryan Mills...","Action,Crime,Thriller","In Istanbul, retired CIA operative Bryan Mills..."
9,3870,1900,The epic tale of a class struggle in twentieth...,"Drama,History",The epic tale of a class struggle in twentieth...
10,203,Mean Streets,"A small-time hood must choose from among love,...","Drama,Crime","A small-time hood must choose from among love,..."
11,10908,Inferno,Eddie Lomax (Jean-Claude Van Damme) is a drift...,"Action,Drama,Romance",Eddie Lomax (Jean-Claude Van Damme) is a drift...
12,517088,Being the Ricardos,Lucille Ball and Desi Arnaz face a crisis that...,"Drama,History",Lucille Ball and Desi Arnaz face a crisis that...
13,37910,Voices of a Distant Star,It is 2046 when a mysterious alien force begin...,"Animation,Science Fiction,Romance",It is 2046 when a mysterious alien force begin...
14,8366,Manitou's Shoe,"Abahachi, Chief of the Apache Indians, and his...","Comedy,Western","Abahachi, Chief of the Apache Indians, and his..."
15,39100,Dragon Ball Z: The World's Strongest,The evil Dr. Kochin uses the dragon balls to r...,"Action,Animation,Science Fiction",The evil Dr. Kochin uses the dragon balls to r...
16,5915,Into the Wild,After graduating from Emory University in 1992...,"Adventure,Drama",After graduating from Emory University in 1992...
17,4258,Scary Movie 5,"Home with their newly-formed family, happy par...",Comedy,"Home with their newly-formed family, happy par..."
18,37834,Knight and Day,A fugitive couple goes on a glamorous and some...,"Action,Comedy",A fugitive couple goes on a glamorous and some...
19,228066,Victor Frankenstein,Eccentric scientist Victor Von Frankenstein cr...,"Drama,Science Fiction,Thriller",Eccentric scientist Victor Von Frankenstein cr...

In [88]:
movies_history.columns

Index(['id', 'title', 'overview', 'genre', 'tags'], dtype='object')

In [89]:
movies_history=movies_history[['id', 'title', 'overview', 'genre']]

In [90]:
movies_history

,id,title,overview,genre
0,332567,The Shallows,"When Nancy is surfing on a secluded beach, she...","Horror,Drama,Thriller"
1,4258,Scary Movie 5,"Home with their newly-formed family, happy par...",Comedy
2,39100,Dragon Ball Z: The World's Strongest,The evil Dr. Kochin uses the dragon balls to r...,"Action,Animation,Science Fiction"
3,727293,The Tender Bar,J.R. is a fatherless boy growing up in the glo...,Drama
4,82675,Taken 2,"In Istanbul, retired CIA operative Bryan Mills...","Action,Crime,Thriller"
5,38365,Grown Ups,After their high school basketball coach passe...,Comedy
6,10908,Inferno,Eddie Lomax (Jean-Claude Van Damme) is a drift...,"Action,Drama,Romance"
7,635731,Pig,A truffle hunter who lives alone in the Oregon...,"Drama,Thriller"
8,37834,Knight and Day,A fugitive couple goes on a glamorous and some...,"Action,Comedy"
9,5915,Into the Wild,After graduating from Emory University in 1992...,"Adventure,Drama"
10,37910,Voices of a Distant Star,It is 2046 when a mysterious alien force begin...,"Animation,Science Fiction,Romance"
11,9385,The Twelve Tasks of Asterix,Asterix and Obelix depart on an adventure to c...,"Family,Animation,Comedy,Adventure"
12,3870,1900,The epic tale of a class struggle in twentieth...,"Drama,History"
13,228066,Victor Frankenstein,Eccentric scientist Victor Von Frankenstein cr...,"Drama,Science Fiction,Thriller"
14,8835,Legally Blonde,"Elle Woods, a fashionable sorority queen, is d...",Comedy
15,517088,Being the Ricardos,Lucille Ball and Desi Arnaz face a crisis that...,"Drama,History"
16,390062,Jungle,"In 1981, an enthusiastic young adventurer foll...","Adventure,Drama,Thriller"
17,203,Mean Streets,"A small-time hood must choose from among love,...","Drama,Crime"
18,8366,Manitou's Shoe,"Abahachi, Chief of the Apache Indians, and his...","Comedy,Western"
19,5991,The Last Laugh,"An aging doorman, after being fired from his p...",Drama

In [91]:
movies_history['tags'] = movies_history['overview'] + movies_history['genre']

In [93]:
movies_history

,id,title,overview,genre,tags
0,332567,The Shallows,"When Nancy is surfing on a secluded beach, she...","Horror,Drama,Thriller","When Nancy is surfing on a secluded beach, she..."
1,4258,Scary Movie 5,"Home with their newly-formed family, happy par...",Comedy,"Home with their newly-formed family, happy par..."
2,39100,Dragon Ball Z: The World's Strongest,The evil Dr. Kochin uses the dragon balls to r...,"Action,Animation,Science Fiction",The evil Dr. Kochin uses the dragon balls to r...
3,727293,The Tender Bar,J.R. is a fatherless boy growing up in the glo...,Drama,J.R. is a fatherless boy growing up in the glo...
4,82675,Taken 2,"In Istanbul, retired CIA operative Bryan Mills...","Action,Crime,Thriller","In Istanbul, retired CIA operative Bryan Mills..."
5,38365,Grown Ups,After their high school basketball coach passe...,Comedy,After their high school basketball coach passe...
6,10908,Inferno,Eddie Lomax (Jean-Claude Van Damme) is a drift...,"Action,Drama,Romance",Eddie Lomax (Jean-Claude Van Damme) is a drift...
7,635731,Pig,A truffle hunter who lives alone in the Oregon...,"Drama,Thriller",A truffle hunter who lives alone in the Oregon...
8,37834,Knight and Day,A fugitive couple goes on a glamorous and some...,"Action,Comedy",A fugitive couple goes on a glamorous and some...
9,5915,Into the Wild,After graduating from Emory University in 1992...,"Adventure,Drama",After graduating from Emory University in 1992...
10,37910,Voices of a Distant Star,It is 2046 when a mysterious alien force begin...,"Animation,Science Fiction,Romance",It is 2046 when a mysterious alien force begin...
11,9385,The Twelve Tasks of Asterix,Asterix and Obelix depart on an adventure to c...,"Family,Animation,Comedy,Adventure",Asterix and Obelix depart on an adventure to c...
12,3870,1900,The epic tale of a class struggle in twentieth...,"Drama,History",The epic tale of a class struggle in twentieth...
13,228066,Victor Frankenstein,Eccentric scientist Victor Von Frankenstein cr...,"Drama,Science Fiction,Thriller",Eccentric scientist Victor Von Frankenstein cr...
14,8835,Legally Blonde,"Elle Woods, a fashionable sorority queen, is d...",Comedy,"Elle Woods, a fashionable sorority queen, is d..."
15,517088,Being the Ricardos,Lucille Ball and Desi Arnaz face a crisis that...,"Drama,History",Lucille Ball and Desi Arnaz face a crisis that...
16,390062,Jungle,"In 1981, an enthusiastic young adventurer foll...","Adventure,Drama,Thriller","In 1981, an enthusiastic young adventurer foll..."
17,203,Mean Streets,"A small-time hood must choose from among love,...","Drama,Crime","A small-time hood must choose from among love,..."
18,8366,Manitou's Shoe,"Abahachi, Chief of the Apache Indians, and his...","Comedy,Western","Abahachi, Chief of the Apache Indians, and his..."
19,5991,The Last Laugh,"An aging doorman, after being fired from his p...",Drama,"An aging doorman, after being fired from his p..."

In [94]:
new_movies_history  = movies_history.drop(columns=['overview', 'genre'])

In [95]:
new_movies_history

,id,title,tags
0,332567,The Shallows,"When Nancy is surfing on a secluded beach, she..."
1,4258,Scary Movie 5,"Home with their newly-formed family, happy par..."
2,39100,Dragon Ball Z: The World's Strongest,The evil Dr. Kochin uses the dragon balls to r...
3,727293,The Tender Bar,J.R. is a fatherless boy growing up in the glo...
4,82675,Taken 2,"In Istanbul, retired CIA operative Bryan Mills..."
5,38365,Grown Ups,After their high school basketball coach passe...
6,10908,Inferno,Eddie Lomax (Jean-Claude Van Damme) is a drift...
7,635731,Pig,A truffle hunter who lives alone in the Oregon...
8,37834,Knight and Day,A fugitive couple goes on a glamorous and some...
9,5915,Into the Wild,After graduating from Emory University in 1992...
10,37910,Voices of a Distant Star,It is 2046 when a mysterious alien force begin...
11,9385,The Twelve Tasks of Asterix,Asterix and Obelix depart on an adventure to c...
12,3870,1900,The epic tale of a class struggle in twentieth...
13,228066,Victor Frankenstein,Eccentric scientist Victor Von Frankenstein cr...
14,8835,Legally Blonde,"Elle Woods, a fashionable sorority queen, is d..."
15,517088,Being the Ricardos,Lucille Ball and Desi Arnaz face a crisis that...
16,390062,Jungle,"In 1981, an enthusiastic young adventurer foll..."
17,203,Mean Streets,"A small-time hood must choose from among love,..."
18,8366,Manitou's Shoe,"Abahachi, Chief of the Apache Indians, and his..."
19,5991,The Last Laugh,"An aging doorman, after being fired from his p..."

In [113]:
# Remove rows with missing values in the 'tags' column
new_data = new_data.dropna(subset=['tags'])

In [114]:
# Remove rows with missing values in the 'tags' column
new_movies_history = new_movies_history.dropna(subset=['tags'])

In [124]:
# Create a TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)

# Fit and transform the movie dataset
tfidf_matrix_movies = tfidf_vectorizer.fit_transform(new_data['tags'])

# Initialize a list to store all recommended movie titles
all_recommended_movies = []

# Iterate through the watch history
for index, history_row in new_movies_history.iterrows():
    # Transform the watch history row using the same vectorizer
    tfidf_matrix_history = tfidf_vectorizer.transform([history_row['tags']])
    
    # Calculate cosine similarity
    similarity_scores = cosine_similarity(tfidf_matrix_history, tfidf_matrix_movies)
    
    # Sort the similarity scores and get the indices of the most similar movies
    sorted_indices = similarity_scores.argsort()[0][::-1]
    
    # Exclude the same movie from the recommendations
    exclude_movie_title = history_row['title']
    sorted_indices = [i for i in sorted_indices if movies.iloc[i]['title'] != exclude_movie_title]
    
    # Append the titles of the top similar movies to the all_recommended_movies list
    all_recommended_movies.extend(list(movies.iloc[sorted_indices]['title']))

# Create a dictionary to store the cumulative similarity scores for each recommended movie
cumulative_scores = {}

# Calculate cumulative scores by summing the similarity scores
for movie in all_recommended_movies:
    if movie in cumulative_scores:
        cumulative_scores[movie] += 1  
    else:
        cumulative_scores[movie] = 1

# Sort movies by cumulative similarity scores in descending order
sorted_movies = sorted(cumulative_scores.keys(), key=lambda x: cumulative_scores[x], reverse=True)

# Get the top 5 movies with the highest cumulative scores
top_5_movies = sorted_movies[:5]

# Print the top 5 recommended movie titles
for i, title in enumerate(top_5_movies, start=1):
    print(f"Recommendation {i}: {title}")

Recommendation 1: Beauty and the Beast
Recommendation 2: Carrie
Recommendation 3: Point Blank
Recommendation 4: Cinderella
Recommendation 5: The Three Musketeers

In [126]:
top_5_movies

['Beauty and the Beast',
 'Carrie',
 'Point Blank',
 'Cinderella',
 'The Three Musketeers']

In [128]:
import pickle

In [129]:
pickle.dump(top_5_movies, open('top_movies_list.pkl', 'wb'))

In [121]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Fit and transform the movie dataset
# tfidf_matrix_movies = tfidf_vectorizer.fit_transform(new_data['tags'])

# # Initialize a list to store recommended movie titles
# recommended_movies = []

# # Iterate through the watch history
# for index, history_row in new_movies_history.iterrows():
#     # Transform the watch history row using the same vectorizer
#     tfidf_matrix_history = tfidf_vectorizer.transform([history_row['tags']])
    
#     # Calculate cosine similarity
#     similarity_scores = cosine_similarity(tfidf_matrix_history, tfidf_matrix_movies)
    
#     # Sort the similarity scores and get the indices of the most similar movies
#     sorted_indices = similarity_scores.argsort()[0][::-1]
    
#     # Exclude the same movie from the recommendations
#     exclude_movie_title = history_row['title']
#     sorted_indices = [i for i in sorted_indices if movies.iloc[i]['title'] != exclude_movie_title]
    
#     # Append the titles of the top similar movies to the recommended_movies list
#     recommended_movies.extend(list(movies.iloc[sorted_indices[:5]]['title']))

# # Print the recommended movie titles
# for i, title in enumerate(recommended_movies, start=1):
#     print(f"Recommendation {i}: {title}")

Recommendation 1: Shall We Dance?
Recommendation 2: I Spit on Your Grave III: Vengeance is Mine
Recommendation 3: Day of the Dead
Recommendation 4: The Warriors Gate
Recommendation 5: Gold
Recommendation 6: Spice World
Recommendation 7: Pet Sematary
Recommendation 8: The New Adventures of Cinderella
Recommendation 9: Beirut
Recommendation 10: Enemy of the State
Recommendation 11: Last Vegas
Recommendation 12: Spellbound
Recommendation 13: Sweet Girl
Recommendation 14: Dragon Ball Z: Wrath of the Dragon
Recommendation 15: Arn: The Knight Templar
Recommendation 16: Alan Partridge: Alpha Papa
Recommendation 17: Shoot the Piano Player
Recommendation 18: The Northman
Recommendation 19: Shadow of a Doubt
Recommendation 20: Rain Man
Recommendation 21: Creep 2
Recommendation 22: The Twilight Saga: Eclipse
Recommendation 23: Blood Ties
Recommendation 24: National Treasure: Book of Secrets
Recommendation 25: Teaching Mrs. Tingle
Recommendation 26: Gangster Squad
Recommendation 27: You Choose!
Recommendation 28: Crank
Recommendation 29: Champions
Recommendation 30: Hoosiers
Recommendation 31: Gemma Bovery
Recommendation 32: The Ides of March
Recommendation 33: BASEketball
Recommendation 34: Society
Recommendation 35: The Outsiders
Recommendation 36: Ice Age: The Meltdown
Recommendation 37: Scanners
Recommendation 38: Tag
Recommendation 39: Drugstore Cowboy
Recommendation 40: Saw V
Recommendation 41: Extinction
Recommendation 42: Parasite
Recommendation 43: Tifosi
Recommendation 44: First They Killed My Father
Recommendation 45: Avengers: Age of Ultron
Recommendation 46: Doghouse
Recommendation 47: Race
Recommendation 48: Up
Recommendation 49: Pooh's Grand Adventure: The Search for Christopher Robin
Recommendation 50: Tangerines
Recommendation 51: Widows
Recommendation 52: Knowing
Recommendation 53: Happy-Go-Lucky
Recommendation 54: Mercy
Recommendation 55: The Witches of Eastwick
Recommendation 56: Sex and the City 2
Recommendation 57: Barfly
Recommendation 58: The Kid
Recommendation 59: The Ghost of Lord Farquaad
Recommendation 60: Asterix & Obelix: Mission Cleopatra
Recommendation 61: How the West Was Won
Recommendation 62: City of God
Recommendation 63: The Battle of Algiers
Recommendation 64: Martin Eden
Recommendation 65: Hard Eight
Recommendation 66: Mirror Mirror
Recommendation 67: The Champion
Recommendation 68: Wild Target
Recommendation 69: Young Frankenstein
Recommendation 70: Drumline
Recommendation 71: She's Gotta Have It
Recommendation 72: The Kissing Booth 3
Recommendation 73: All I See Is You
Recommendation 74: Anatomy
Recommendation 75: Return to Sleepaway Camp
Recommendation 76: The Hunting Party
Recommendation 77: The Courier
Recommendation 78: Invasion U.S.A.
Recommendation 79: Luxo Jr.
Recommendation 80: The Secret Life of Pets
Recommendation 81: Robin Hood: Men in Tights
Recommendation 82: Double Lover
Recommendation 83: The Witches of Eastwick
Recommendation 84: Super Troopers 2
Recommendation 85: Bitch Slap
Recommendation 86: Polaroid
Recommendation 87: La Cage aux Folles
Recommendation 88: Payback
Recommendation 89: Skins
Recommendation 90: Get Carter
Recommendation 91: Robin Hood: Prince of Thieves
Recommendation 92: The Blob
Recommendation 93: Little Big Man
Recommendation 94: The Searchers
Recommendation 95: Johnny Guitar
Recommendation 96: The Mechanic
Recommendation 97: Small Fry
Recommendation 98: The Student
Recommendation 99: Office Space
Recommendation 100: Underdogs